#!/usr/bin/make
# quick-in-dirty test runners

test1:
	gcc test1.c -lz -llimeade -o test1.out
	./test1.out

test2:
	gcc test2.c -lz -llimeade -o test2.out
	./test2.out

clean:
	rm test*.out

all: test1 test2
