// limecap.h
//
// Copyright (C) 2026 Roan Rothrock
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#include<stdint.h>

// This file is provided alongside liblimeade. It represents a library for
// creating/modifying/reading Limecap files, which are files designed to hold
// Limeade data. While it is a part of liblimeade, the API it defines is
// completely removed from the rest of liblimeade.

/*** DATA TYPES ***/

// the magic of a .limecap file
#define LIMECAP_MAGIC_RAW "LIME!\n"
static char LIMECAP_MAGIC[7]; // populated elsewhere

// the header of a .limecap file
typedef struct
{
  uint64_t ts;             // the time that the file was created (in UNIX time)
  uint8_t limecap_ver;     // the the version of Limecap the file obeys
  uint8_t limeade_maj_ver; // the major version number of Limeade
  uint8_t limeade_min_ver; // the minor version number of Limeade
  char *short_description; // small comment about the file
  char *long_description;  // long comment about the file
} LIMECAP_HEADER;

// detailed timestamps
typedef struct
{
  uint64_t s;  // seconds (UNIX time)
  uint16_t ms; // milliseconds from last second
  uint16_t ns; // nanoseconds from last millisecond
} LIMECAP_TS;

// header for each packet
typedef struct
{
  size_t index;       // the index of the packet within the file
  size_t len;         // the size of the packet entry in the file
  LIMECAP_TS ts_sent; // when the packet was sent
  LIMECAP_TS ts_recv; // when the packet was received
  LIMECAP_TS ts_srlz; // when the packet was serialized
  uint8_t type;       // the type of the packet
  void *data;         // the data in the packet (of size `len`)
} LIMECAP_PACKET;

// context for each Limecap file open
typedef struct
{
  char mode; // the mode of the file's opening ("r", "w", "a")
  int fd;    // file descriptor of the file
  size_t nr_events;   // number of events found within the file
  size_t **event_szs; // sizes of event data 
} LIMECAP_CONTEXT;


/*** INIT ***/

// the following 3 functions all do the same thing: open a .limecap file
// however, they all do so for different reasons
// _r: readonly
// _w: reading, altering preexisting information, and adding new information
// _a: append only
// all return a LIMECAP_CONTEXT item that is required for subsequent calls in
// the API
LIMECAP_CONTEXT limecap_open_r(const char *path);
LIMECAP_CONTEXT limecap_open_w(const char *path);
LIMECAP_CONTEXT limecap_open_a(const char *path);

// for closing a file:
void limecap_close(LIMECAP_CONTEXT ctx);


/*** R & W ***/

// accessing the header
int limecap_write_header(LIMECAP_CONTEXT ctx, LIMECAP_HEADER new);
LIMECAP_CONTEXT limecap_read_header(int *status);

// generating indexes
// after a file is opened and before any packet data is read, first indexes
// must be generated. That is, that this library generates an index of every
// packet described in the file, so that they can all be read to/written from
// according to their index value
// indexes are managed internally, and are generated by calling the following:
int limecap_gen_indexes(LIMECAP_CONTEXT ctx);

// accessing indexes
LIMECAP_PACKET limecap_r_index(LIMECAP_CONTEXT ctx, unsigned int index);
int limecap_w_index(LIMECAP_CONTEXT ctx, unsigned int index, LIMECAP_PACKET new);

// appending
int limecap_append(LIMECAP_CONTEXT ctx, LIMECAP_PACKET new);

