name: C/C++ CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install zlib
      run: sudo apt install zlib1g-dev
    - name: make install
      run: sudo make install
    - name: make test
      run: gcc tests/test1.c -lz -llimeade -o test
    - name: run test
      run: ./test
